### ISSUE TITLE
Followed the "Get started under Linux" guide, can't get LEDs to blink

### ISSUE THREAD

**Issue by kayprish** [OLIMEX/iCE40HX1K-EVB#17]
I've tried following this guide:

https://www.olimex.com/wiki/ICE40HX1K-EVB#Get_started_under_Linux

So far, I believe I've managed to get everything working, the 32u4 is working, I've managed to upload iceprog.ino to it.
I've managed to install iceprogduino on my system. As well as all the dependencies.

I've copied this directory to another location: https://github.com/OLIMEX/iCE40HX1K-EVB/tree/master/demo/ice40hx1k-evb
This is the demo of the board that's supposed to display two blinking LEDs.

I ran `make` and `make prog`. The output indicates no issue. However when I program the board, I don't get blinking LEDs 1 and 2.
Instead they both give off a faint light that doesn't change, shown in the image below.

The board:
![The board](https://github.com/user-attachments/assets/1da46f94-d763-47c8-9c36-d5ace1c7673b)

**Comment by DanKoloff** [comment]
The demo was made for iCE40HX1K and you seem to have iCE40HX8K. The LEDs are at different pins, probably just using the proper pins for the LEDs would do the job. 

In iCE40HX1K the LEDs are at pins  41 and 51. In iCE40HX8K the LEDs are at M12 and R16.

You need to make a pcf file for the 8K board, use the 1K as a template:

https://github.com/OLIMEX/iCE40HX1K-EVB/blob/master/demo/ice40hx1k-evb/ice40hx1k-evb.pcf

Refer to the PDF exports of the schematic.

Try with this pcf:

https://github.com/OLIMEX/iCE40HX8K-EVB/blob/master/demo/ice40hx8k-evb/ice40hx8k-evb.pcf

**Comment by kayprish** [comment]
Will try, I don't have access to the board currently but I will close as soon as I try and it works out.

**Comment by kayprish** [comment]
Yep, my mistake, I just deleted the whole HX1K example directory, and replaced it with the contents of this directory.
https://github.com/OLIMEX/iCE40HX8K-EVB/tree/master/demo/ice40hx8k-evb
Everything works, closing this issue.
