### ISSUE TITLE
Request guide to program FPGA board with generic Arduino

### ISSUE THREAD

**Issue by electronut** [OLIMEX/iCE40HX1K-EVB#2]
The current documentation assumes that Olimexduino is used as a programmer with the custom cable.

This board would be much more user friendly if some guidance was provided on making it work with a generic Arduino - for example an Arduino Pro Mini.

**Comment by DanKoloff** [comment]
OLIMEXINO-328 is quite generic. It is quite similar to Arduino UNO R3. You can use the guide as a reference and use any Arduino board. Furthermore, it looks like Arduino Pro Mini is a retired product: https://store.arduino.cc/arduino-pro-mini

**Comment by electronut** [comment]
Pro Mini clones are still widely used. I also tried with an Arduino Uno + level shifter, but was unable to make it work. I'll try some more and post my results. 

I've seen someone using Raspberry Pi's SPI ports with icestorm tools to program this board. Any help there would be very useful as well. 

I think having multiple options to program this board could be very helpful. Thanks.

**Comment by electronut** [comment]
I really wish some sort of programmer (USB/SPI or serial) was embedded in this board. At this point I've given up and am getting the dev board from Lattice.
