### ISSUE TITLE
ADC module availability

### ISSUE THREAD

**Issue by kelu124** [OLIMEX/iCE40HX1K-EVB#3]
Hi Olimex!
I saw you had a ICE40 100Msps ADC extension board - but couldn't find the link to the repo. Would you still have it?
Thanks in advance!

**Comment by TsvetanUsunov** [comment]
all modules are here https://www.olimex.com/Products/FPGA/iCE40/

**Comment by DanKoloff** [comment]
@kelu124 I removed it by mistake last week, it is now up again. Sorry.

**Comment by kelu124** [comment]
Thanks a bunch!
