### ISSUE TITLE
SRAM programming

### ISSUE THREAD

**Issue by kdltr** [OLIMEX/iCE40HX1K-EVB#4]
Any chance to get iceprogduino to be able to program the SRAM directly instead of rewriting the SPI flash? That would make the development process a lot faster.

**Comment by frantony** [comment]
@kdltr 
Please see this commit: https://github.com/furrtek/iCE40HX1K-EVB/commit/30373b5e3069b1ba789a1a03d4a58df0f537a507

**Comment by kdltr** [comment]
@frantony I know, we did that together, but it needs more testing. ^^
