### ISSUE TITLE
Programing ICE40HX1K-EVB

### ISSUE THREAD

**Issue by ilkerparmaksiz** [OLIMEX/iCE40HX1K-EVB#6]
HI there, I am trying to program this FPGA by arduino due. I uploaded the initial sketch to arduino due after that , the LED close to PGM1 connections on the board turn on.  Whenever I try to program it by using example on ICE40HX1K-EVB, it connects to arduino due , says bulk erased , and programing ...  I also can see the RX led on the arduino blinks. However ,this continues forever , and i am not sure what to do next about this. I wonder if you guys have any suggestion?  For SPIFlash i am using latest version.

**Comment by DanKoloff** [comment]
What sketch do you upload to the Due? Our programmer sketch is meant for OLIMEXINO-32u4 and might not work properly without changes with other boards.

**Comment by ilkerparmaksiz** [comment]
i upload the iceprog sketch from the ice40hx1-evb library. For Arduino due,  i am making  following changes;
#define CDONE 12
#define RESET 11
#define CS  10
The problem i think is I somehow can not make successful connection with flash memory. I use the SPIFlash Memory library that they recommend in the sketch, It keeps saying " flash memory chip is not initialized  check wiring or may chip is not supported"

**Comment by ilkerparmaksiz** [comment]
also flash memory returning "0" for every SPI transfer

**Comment by ilkerparmaksiz** [comment]
we also have test it  with  raspberry pi 3 as it is shown on the olimex page. However we get the same response Flash memory is not detected. How possible is the flash memory has problem?

**Comment by ilkerparmaksiz** [comment]
also the following connections you guys give for the programming connector is wrong.
https://www.olimex.com/wiki/File:ICE40PGM.jpg
those are the correct connections i have tested by hand, and get them from ur schematics
https://pasteboard.co/HqZ9sSj.png.

**Comment by DanKoloff** [comment]
I can't see the discrepancy in the pictures.  Looks like one of the pictures is rotated... but the connections and the layout seem the same. The plastic connector BH10S has an arrow that points pin #1: https://kamami.pl/205-large_default/bh10s.jpg
